rrhh_default:
    path: /index/{name}
    defaults: { _controller:RRHHBundle:Default:index }
    
rrhh_help:
    path: /help/{help}
    defaults: { _controller:RRHHBundle:Default:help }
    
rrhh_info:
    path: /info/{name}/{lastName}/{id}
    defaults: { _controller:RRHHBundle:Info:index, name:candy, lastName:null, id:null }
    
rrhh_estatico:
    path: /estatico/{pagina}
    defaults: { _controller:RRHHBundle:Info:pagina_estatica, pagina:quien }
    
    
producto_crear:
    path: /producto/new
    defaults: { _controller:RRHHBundle:Producto:new }
    
producto_listar:
    path: /producto/listar
    defaults: { _controller:RRHHBundle:Producto:productosAll }
    
producto_mostrar:
    path: /producto/show/{id}
    defaults: { _controller:RRHHBundle:Producto:productoShow }
    
producto_delete:
    path: /producto/delete/{id}
    defaults: { _controller:RRHHBundle:Producto:productoDelete }
    
producto_editar:
    path: /producto/editar/{id}/{nombre}
    defaults: { _controller:RRHHBundle:Producto:productoEdit }
    